name: Swift

on:
  push:
    branches:
    - features/*
  pull_request:
    branches:
    - main
    - develop
    - release

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        pod install --repo-update --clean-install
        xcodebuild clean build -workspace Market.xcworkspace -scheme Market -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
    - name: Run tests
      run: |
        xcodebuild clean test -workspace Market.xcworkspace -scheme Market -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
