name: Swift

on:
  push:
    branches:
    - features/*
  pull_request:
    branches:
    - main
    - develop
    - release

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        pod install --repo-update --clean-install --project-directory=Market/
        xcodebuild test -project Market.xcodeproj -scheme Market -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
    - name: Run tests
      run: swift test -v
